[package]
name = "cuda_kernel_mandel"
version = "0.1.0"
authors = ["bumzack"]
edition = "2018"

[build-dependencies]
ptx-builder = "0.5"

[target.'cfg(target_os = "cuda")'.dependencies]
ptx-support = { git  = "https://github.com/denzp/rust-ptx-support" }

[dependencies.common]
path = "../common"
